### ISSUE TITLE
Zustandsauswahl

### ISSUE THREAD

**Issue by HilliousPrey** [jrie/sqstorage#1]
Guten Morgen Jan :)

Ich bin auf der Suche nach einer "kleinen" Inventarisierung auf dein GIT gestoßen.

Erst mal herzlichen Dank, dass du sqstorage zur Verfügung stellst 👍 Es ist eigentlich alles vorhanden, was man(n) braucht. 

Ich hätte nur eine Anfrage/Verbesserung, welche vielleicht noch interessant wäre. 

Wäre es möglich, im nächsten Release, eine Möglichkeit einzubauen den Zustand einen Artikels mit anzugeben? (neu, gebraucht, refurbished)

LG
Tobias

**Comment by jrie** [comment]
Hallo Tobias,

freut mich wenn dir sqstorage gefällt. Grundsätzlich wäre es möglich deinen Vorschlag umzusetzen und ich kann diesen gern berücksichtigen.

In der Zwischenzeit gäbe es die Möglichkeit den Zustand eines Artikels in einer "Unterkategorie" anzulegen.

Das heißt, wenn du einen Artikel einträgst oder bearbeitest, trage als Unterkategorie "Neu", "Gebraucht" oder "Refurbished" ein, im Feld "Unterkategorien" in einer Eintragemaske für Artikel.

Du kannst dann alle Artikel in der jeweiligen Unterkategorie auflisten lassen die sich darunter befinden, genau wie die Suche nach Hauptkategorien, lassen sich auch Unterkategorien (durch)suchen und explizit anzeigen lassen.

Vorteil wäre hier, dass du die Unterkategorie nur einmalig eingeben und für alle folgenden Artikel diese Unterkategorie verwenden bzw. zusätzlich anwenden kannst.

**Comment by jrie** [comment]
c236d13 adds the functionality to add custom data fields, which can be used to set custom attributes to items.

c236d13 fügt Datenfelder hinzu, diese ermöglichen das hinuzfügen von eigenen Attributen für Kategorien und Gegenstände.
