### ISSUE TITLE
Problem beim Login bei falschen Zugangsdaten

### ISSUE THREAD

**Issue by Launhardt** [jrie/sqstorage#100]
Hallo zusammen,
in meiner kleinen Testumgebung ist mir etwas aufgefallen. Beim Login mit falschen Zugangsdaten erzeugt es einen Fehler:
Fatal error: Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in C:\xxxxxx\htdocs\sqstorage\support\tools_class_users.php:18 Stack trace: #0 C:\xxxxxx\htdocs\sqstorage\support\tools_class_users.php(61): USERS::AllowLogin('test', 0) #1 C:\xxxxxx\htdocs\sqstorage\login.php(165): USERS::Login('test', 'test', NULL) #2 {main} thrown in C:\xxxxxx\htdocs\sqstorage\support\tools_class_users.php on line 18
 Benutztes PHP8.1.10

**Comment by jrie** [comment]
Thanks for the report, it is fixed! :+1:
