### ISSUE TITLE
Permission denied wenn sqstorage als Docker Container ausgeführt wird

### ISSUE THREAD

**Issue by web-rpi** [jrie/sqstorage#102]
**Beschreibung des Problems:**

Ich habe versucht, sqstorage Version 0.2.0 als Docker-Container zu verwenden, indem ich die folgenden Befehle ausgeführt habe:

wget https://github.com/jrie/sqstorage/archive/refs/tags/0.2.0.zip
unzip 0.2.0.zip
mv 0.2.0/* ~/docker/sqstorage/
cd ~/docker/sqstorage/
docker compose build
docker compose up -d

Wenn ich nun im Webbrowser auf sqstorage navigiere, erhalte ich die folgende Fehlermeldung:

Warning: copy(languages/locale/de_DE/LC_MESSAGES/messages_1657980536.mo): failed to open stream: Permission denied in /app/support/language_tools.php on line 42

Warning: require_once(/app/support/dba.php): failed to open stream: Success in /app/login.php on line 11

Fatal error: require_once(): Failed opening required './support/dba.php' (include_path='.:/usr/local/lib/php') in /app/login.php on line 11

Ich vermute dies hängt mit den Berechtigungen zusammen. 
Leider weiß ich nicht wo ich hier ansetzen soll.
Im Container "sqstorage020-web-1" existiert der Benutzer "www-data" nicht um die Berechtigungen wie sie in setfolderpermissions.sh angegeben sind zu vergeben.

Ich bitte um Hilfe.

**Comment by jrie** [comment]
Hallo. Ich bin leider kein Experte mit Docker und es wurde nicht regelmäßig getestet. Ich glaube es muß in der *Dockerfile* Datei im Hauptordner der Benutzer festgelegt werden

 Ungefähr so:
*USER www-data*
am Ende einfügen.

Leider kann ich dies nicht aktuell testen.

**Comment by web-rpi** [comment]
Ich habe das Dockerfile im sqStorage Projekt wie folgend angepasst:
`FROM php:7-fpm-buster

COPY ./ /app/
RUN usermod -u 1000 www-data
RUN groupmod -g 1000 www-data

RUN chown www-data:www-data -R /app/

VOLUME /app

RUN docker-php-ext-install mysqli
RUN docker-php-ext-install gettext

RUN apt-get update && apt-get install -y zlib1g-dev libicu-dev g++

RUN docker-php-ext-configure intl
RUN docker-php-ext-install intl`

[https://stackoverflow.com/questions/36824222/how-to-change-the-nginx-process-user-of-the-official-docker-image-nginx](url)

Nach neuem Bauen des Containers ist nun der Berechtigungsfehler verschwunden.
Leider erhalte ich dennoch Fehler...


Warning: require_once(/app/support/dba.php): failed to open stream: Success in /app/login.php on line 11

Fatal error: require_once(): Failed opening required './support/dba.php' (include_path='.:/usr/local/lib/php') in /app/login.php on line 11

**Comment by jrie** [comment]
Ich hab es nicht testen können aber die Zeile 11 in *login.php* müsste korrigiert werden.

Aus: *require_once('./support.dba.php');*
Den Teil *./* entfernen.

Der *"require_once"* mit dieser Schreibweise befindet sich ebenfalls in anderen PHP Dateien des Hauptordners.

Teste bitte, ob der Fehler nach der Anpassung der *Login.php* funktioniert. Ist dem so, müssen die anderen Dateien ebenfalls angepasst werden.

**Comment by web-rpi** [comment]
die Zeile 11 der login.php habe ich angepasst.
Ich konnte auch feststellen dass eine dba.php Datei im Containerimage nicht existiert... lediglich ein Ordner namens dba.php.
Es sieht so aus als wäre auch das docker-compose.yml File in Zeile 9 fehlerhaft.
Scheinbar wird hier ein Ordner angelegt anstatt die dba.php kopiert.
Wo wird eigentlich die dba.php erzeugt?

**Comment by web-rpi** [comment]
If docker is used, dba.php must be copied from the support/ directory to the main sqstorage directory before build it.
In the pullrequest #105  the permission error of the webserver was fixed.
