### ISSUE TITLE
HTTP ERROR 500 and black page after submitting "db connection" data during installation procedure

### ISSUE THREAD

**Issue by sdi2001** [jrie/sqstorage#103]
when doing a fresh installation I am landing onto this page:

![image](https://github.com/jrie/sqstorage/assets/42043949/afd7aa13-005b-4dc7-aee1-ff39a25004fe)

I am keeping all default settings untouched - I created in advance a database tlv and a user tlvUser with the correct passwort written here in the readme.
After clickling on "Verbindungsdaten eintragen" I am getting a black page with prompted "HTTP ERROR 500"

![image](https://github.com/jrie/sqstorage/assets/42043949/2cf737f1-1452-451c-b1b0-bf336842d749)

Why?

**Comment by jrie** [comment]
Hello, from a fresh checkout, I cannot reproduce this issue. What kind of software and operating system do you use? For example Nginx, Apache on Windows, Unix or macOS, and which PHP and SQL version?

**Comment by sdi2001** [comment]
Servus Jan,

I am running this on a VM with  Ubuntu 22.04.3 LTS 

Apache Version
    Server version: Apache/2.4.52 (Ubuntu)
    Server built:   2023-05-03T20:02:51

PHP Version 
   PHP 8.1.2-1ubuntu2.14 (cli) (built: Aug 18 2023 11:41:11) (NTS)
   Copyright (c) The PHP Group
   Zend Engine v4.1.2, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.2-1ubuntu2.14, Copyright (c), by Zend Technologies

mySQL Version 
mysql  Ver 8.0.34-0ubuntu0.22.04.1 for Linux on x86_64 ((Ubuntu))


BR
Dieter

**Comment by jrie** [comment]
Hello @sdi2001 - I tested a fresh installation in Ubuntu 22.04.3

For a short debugging session, you can review the Apache2 errors and logs here:
*/var/log/apache2/error.log*

I installed the following packages:
- php8.1-fpm
- php8.1-intl

*php-fpm* has to be enabled in Apache use this:
**a2enmod proxy_fcgi setenvif**
**a2enconf php8.1-fpm**

And reload Apache using: *sudo service apache2 restart*

Now, in order for the database to be created properly, you have to grant:
*Data* and *Structure* permission in mySQL for the database user. Only "Data" permission will not do the job.

I also would recommend, to start with a fresh checkout of sqStorage.
If you have any questions, let me know.
