### ISSUE TITLE
Uncaught mysqli_sql_exception: Out of range value for column 'amount'

### ISSUE THREAD

**Issue by Foxconn11** [jrie/sqstorage#104]
Hey there,

we using sqStorage for a small Company wich does SMD Pick and Place, PCB Manufracturing in general. Now we came to a problem regarding the Database. We are inserting all our SMD components and at some point we came to a Error 500 Page. Apache error Log said the following:

`[Thu Dec 21 07:13:08.481092 2023] [proxy_fcgi:error] [pid 3309] [client 192.168.188.26:63850] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught mysqli_sql_exception: Out of range value for column 'amount' at row 1 in /var/www/html/sqstorageSMD/vendor/SergeyTsalkov/meekrodb/db.class.php:671\nStack trace:\n#0 /var/www/html/sqstorageSMD/vendor/SergeyTsalkov/meekrodb/db.class.php(671): mysqli->query()\n#1 /var/www/html/sqstorageSMD/vendor/SergeyTsalkov/meekrodb/db.class.php(630): MeekroDB->queryHelper()\n#2 /var/www/html/sqstorageSMD/vendor/SergeyTsalkov/meekrodb/db.class.php(631): MeekroDB->prependCall()\n#3 /var/www/html/sqstorageSMD/vendor/SergeyTsalkov/meekrodb/db.class.php(318): MeekroDB->query()\n#4 /var/www/html/sqstorageSMD/vendor/SergeyTsalkov/meekrodb/db.class.php(82): MeekroDB->update()\n#5 /var/www/html/sqstorageSMD/entry.php(206): DB::update()\n#6 {main}\n  thrown in /var/www/html/sqstorageSMD/vendor/SergeyTsalkov/meekrodb/db.class.php on line 671', referer: http://192.168.188.100/sqstorageSMD/entry.php`

The Problem i found is that in the Table headCategories and storages the field "amount" is set to SMALLIT wich only allows a unsigned value of 65535. Setting this to BIGINT will allow maximum of 9223372036854775807

Changing this solved the Problem. Wanted to write this down if someone has the same Problem or maybe for chainging the DB setup for the next revision.

Server version: Apache/2.4.52 (Ubuntu)
mysql  Ver 8.0.35-0ubuntu0.22.04.1 for Linux on x86_64 ((Ubuntu))
PHP 8.1.2-1ubuntu2.14

**Comment by jrie** [comment]
I added a database update in commit 5571f55cc8903e2433af7551830575ce61994af0 which rewrites the amounts to "bigint" types:
- "headCategories" amount
- "storages" amount
- "item" amount

Closing this issue. Thank you for reporting!
