### ISSUE TITLE
Gegenstand(typ) in mehreren Lagern

### ISSUE THREAD

**Issue by F1reF0x** [jrie/sqstorage#12]
Hallo,

ich teste derzeit sqstorage und denke, dass es für eine einfache Lagerverwaltung alles beinhaltet ohne viel Schörkel und dazu flink ist. Danke hierfür. 

Eine Sache ist mir aber aufgefallen, die vielleicht Einzug halten sollte: es wäre schön, wenn ein Gegenstand/Gerät sich in mehreren "Lagern" mit jeweils einer Menge befinden würde. Im Lager A befinden sich zB. 5x Patchkabel 1m, ich bewege 2 Stück  in Lager B, bleiben 3 in A. Derzeit ist es lediglich möglich den Gegenstand neu mit passender Anzahl und anderer Bezeichnung in B anzulegen und in Lager A die Menge entsprechend zu entfernen, da ein Gegenstand nur in einem Lager sein darf. Ich hab zB. 3 Schubladen, auf denen sich USB und Patchkabel verteilen, wo diese Abbildung leider nicht so funktioniert. Ein Entfernen auf 0 ist ebenso zumindest in meinen Tests leider nicht möglich, wäre aber hilfreich.

Gruß,
FireFox

**Comment by jrie** [comment]
The current solution by #17 is one kind of workaround to set the number of items to transfer in a storage.

I would like to add this functionality into `transfer.php` where a plus/minus allow to set the amount if not 1. And also the ability to merge items based on a additional selection. It would be possible to leave the prompt in `index.php` or removing it and only add this feature into the `transfer.php`.

**Comment by jrie** [comment]
Strangely enough, this feature introduce here: 8c50f51c7ad45614d2aa8cdc502a4a5b7a429be1 .. seems to be broken at the moment due to other commits?

**Comment by jrie** [comment]
Resolving as fixed, merging and or creation, if not present on transfer, was added.
