### ISSUE TITLE
.editorconfig for formatting standards?

### ISSUE THREAD

**Issue by Darksider3** [jrie/sqstorage#14]
Would'nt it be awesome if everyone can use automated code formatting already approved by the maintainer? :)

Meet the [editorconfig format!](https://editorconfig.org/)
I would propose something easy e.g.
```
root = true
[*]
end_of_line = lf
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true
indent_style = space
indent_size = 2

[*.{diff,md}]
trim_trailing_whitespace = false
```
placed directly in the base directory of this repo :)

**Comment by jrie** [comment]
I agree, a general styling config is awesome. Added. Thank you @Darksider3
