### ISSUE TITLE
UX: nicer dropdowns

### ISSUE THREAD

**Issue by n1trux** [jrie/sqstorage#2]
Dropdowns would be way nicer if you could search in them.

Examples:
* https://semantic-ui.com/modules/dropdown.html#search-selection
* https://select2.org/searching

**Comment by jrie** [comment]
I will work out a implementation for this and agree that a search for lot of different values will improve the overall feeling and come in handy in larger scale usage with more data.

**Comment by jrie** [comment]
A custom dropdown has been implemented, replacing regular "selects", also multiple support.
https://github.com/jrie/sqstorage/blob/master/js/dropDown.js

This dropdowns also can be searched.

Video demo:
https://www.picflash.org/picture.php?key=TL4K7C&action=show

**Comment by jrie** [comment]
Added keyboard navigation inside dropdowns: https://www.picflash.org/picture.php?key=H69UFX&action=show

**Comment by jrie** [comment]
Custom dropdowns to the rescue! :+1:
They can be interactively searched and selected, also multiple selections are supported.
