### ISSUE TITLE
make it possible to create admin user through env variables

### ISSUE THREAD

**Issue by n1trux** [jrie/sqstorage#20]
I propose variables called `SQSTORAGE_ADMIN_USER` and `SQSTORAGE_ADMIN_TOKEN` to create the admin user on first start, if it doesn't exist. The password would be set to `SQSTORAGE_ADMIN_TOKEN` and upon login the user would be immediately prompted to reset their password.

Maybe we could also include a "password reset" function for the admin user account and have a separate `reset.php?username=admin` page where they could enter their token to reset the password? To make this more secure, the token could be generated on first start if it's empty, we could prompt the user to remove it when they have changed their password or it would have to be at least 42 characters long.

**Comment by X-Coder** [comment]
Why is something like this needed? If you have a prompt for reset, then you could just prompt for the username there too, if no prompt this would mean you would have to store the password in cleartext at some place.

Password-reset is already working (if mail can be send). If I don't know my password, the last thing I would remember is the token :)

**Comment by n1trux** [comment]
You could probably just reset the admin user's password by doing

```
UPDATE users SET password = '' WHERE id = 1;
```

Within the database.

If you host this and someone creates an admin user right when you have set it up but didn't visit the page yet, you're effectively locked out of your own installation.

But I suppose you could just block their IP and create a new admin user… or hash the password yourself.
