### ISSUE TITLE
Please add a REST API

### ISSUE THREAD

**Issue by n1trux** [jrie/sqstorage#23]
With a REST API you could programmatically extract information from sqstorage and write scripts or client applications to enter/withdraw items.

E.g. a use case could be automatically removing a bottle of water if you scan it with a barcode scanner. This way an inventory can be kept easily.

REST APIs also make programming additions to the software easy. You don't have to modify the source code of sqstorage but can write your own add-ons without interfering with the lean structure we aim to have for sqstorage.

An API also helps keeping the functional base of the application small. If you have to create new endpoints for every new feature and have to discuss whether to actually include it in your API, you think more thoroughly about adding said feature.

REST APIs also add structure and a clear way to interface with the backend through the frontend.

**Comment by jrie** [comment]
Could you add a description on why and what you think could and would be beneficial?

**Comment by n1trux** [comment]
I added some of my reasons. I'll also be happy to provide further resources.

Here's a list of resources I used for my whitepaper about maintainability with the MVC application paradigm in synergy with REST APIs:

* [REST vs. RPC: what problems are you trying to solve with your APIs?](https://cloud.google.com/blog/products/application-development/rest-vs-rpc-what-problems-are-you-trying-to-solve-with-your-apis) – Google Cloud blog by Martin Nally
* [Undisturbed Rest – A guide to designing the perfect API (PDF)](https://www.mulesoft.com/sites/default/files/resource-assets/ebook-UndisturbedREST_v1.pdf)
* [Pro PHP MVC](https://www.apress.com/gp/book/9781430241645)
* [REST in practice](http://restinpractice.com/)
* [Justice Will Take Us Millions Of Intricate Moves](https://www.crummy.com/writing/speaking/2008-QCon/act3.html) – Richardson Maturity Model explained by the author
