### ISSUE TITLE
Entry fields don't line up properly

### ISSUE THREAD

**Issue by n1trux** [jrie/sqstorage#24]
Sometimes the dropdowns are in front of the entry fields, sometime behind. They're misaligned against one another, which makes the whole application look rather crooked.

Look at this for example:

![screenshot for clarity](https://user-images.githubusercontent.com/7255542/71766877-3f34fa80-2f05-11ea-88bc-81a45b5fc326.png)

**Comment by jrie** [comment]
Should be resolved in commit 3c6496039ea56b01e2ba11a73bc7d4ea4d9dca1b in `css/base.css` using line-height.

**Comment by jrie** [comment]
d8cdc5c should improve the alignment of custom dropdown fields display
