### ISSUE TITLE
The URLs are ugly

### ISSUE THREAD

**Issue by n1trux** [jrie/sqstorage#25]
We could make them prettier by rewriting them! I think this would look pretty good:

| URL | target |
| ------ | -------  |
| /items/ | inventory.php |
| /items/new | index.php |
| /categories/ | categories.php |
| /categories/1 | inventory.php?category=1 |
| /subcategories/ | subcategories.php |
| /subcategories/1 | inventory.php?subcategory=1 |
| /settings/ | settings.php |
| /datafields/ | datafields.php |

With a [REST API](./23) this could be made even better.

I suppose we should add a configuration option in a `config.php` for this:

```
define('ENABLE_URL_REWRITE', false);
```

If it's false, the regular PHP files are used; if it's true, the URLs the application sends to the user are looking like my proposal above.

**Comment by jrie** [comment]
Clean urls have been added by default and rewriting is done using the Apache's mod_rewrite.

Please review 1ae3a07 and 4985a2b . Im pretty sure Nginx has to be configured accordingly in addition?

**Comment by jrie** [comment]
nginx.conf has been update @ 10b799b
Please give it a test run.

**Comment by jrie** [comment]
I close this issue. Please reopen if you find any bugs.
