### ISSUE TITLE
There's no way to know where in the application you are right now

### ISSUE THREAD

**Issue by n1trux** [jrie/sqstorage#26]
Locations where the current part of the application could be displayed:

* navigation bar – highlight where you are right now, e.g. by underlining or making the entry bold
* site title – add a prefix, e.g. the category's name
* site header – below/besides the sqstorage logo
* above the content

I think the best would be highlighting the current page in the navbar and adding it to the site's title. Both the header and above the content would duplicate UI elements and steal valuable space.

**Comment by jrie** [comment]
7e6ca9b adds highlighting of the current navigation item and also the document title is providing some informatiion.

**Comment by jrie** [comment]
I close the issue for now. As highlighting of the navigation items has been added.
