### ISSUE TITLE
UX: search bar position and behaviour

### ISSUE THREAD

**Issue by n1trux** [jrie/sqstorage#3]
Search would probably look better on the right side. Also I'd use a sliding search like https://codepen.io/ArnaudBalland/pen/qEgvBR, only with a faster animation and that you can click into it (so that not the search button is on top, but the input field).

**Comment by jrie** [comment]
I agree about the search placement and the search is now on the right side of the screen.

What I do not agree with is the usage of an animation, this I feel is rather disturbing for the usage of the search.

**Comment by jrie** [comment]
Closing issue, because some UI change happened.
