### ISSUE TITLE
make it possible to show thumbnails in Lists

### ISSUE THREAD

**Issue by dex2000** [jrie/sqstorage#39]
button "contains images" should be possible to replaced with image-thumbnail.

in storage-list too, there is missing now the "contains images"

**Comment by jrie** [comment]
I am wondering about the implementation, at the momemt of writing the inventory and categorie views do not have much space available. So for showing a thumbnail, some other way has to be found. I could imagine some hover "tooltip" containing a thumbnail when hovering the mouse over the "hasImages" icon.
