### ISSUE TITLE
nicht ausgefüllte Felder sollten kursiv gesetzt sein

### ISSUE THREAD

**Issue by dex2000** [jrie/sqstorage#41]
oder anderweitig abgesetzt, der aktuelle Kontrast ist nahezu nicht zu erkennen. 
das gilt auch für obligatorische Felder, dort halte ich andere Farbe (rot) für sinnvoll

**Comment by jrie** [comment]
Possible fix f96be1e050420f8560234437bd3682606b1476d3 .
Required fields are now italic and colored red.

**Comment by dex2000** [comment]
not required fields should be italic too
