### ISSUE TITLE
checkbox im Aufklappfeld Unterkategorie nutzlos

### ISSUE THREAD

**Issue by dex2000** [jrie/sqstorage#43]
Wenn ich einen Artikel erstelle, der mehrere Unterkategorien hat, dann hab ich im Aufklappfeld so schöne Checkboxen.
Die machen aber weder beim neu erstellen noch beim Ändern irgendetwas.
Das ganze funktioniert auch andersrum nicht, wenn ich manuell im Eingabefeld etwas ändere, dann ändert sich die checkbox nicht.

**Comment by jrie** [comment]
I do not quite understand the issue, can you please provide screenshots and the URL you are visiting when this occurs.

**Comment by dex2000** [comment]
Browser Firefox (60.0ESR,68.0ESR,77.0.1)
selecting with keyboard works as expected, mouse-select not
