### ISSUE TITLE
Anzahl Gegenstände etwas "komisch"

### ISSUE THREAD

**Issue by dex2000** [jrie/sqstorage#48]
Ich halte die Anzahl Gegenstände sowohl in Kategorien [hier stand Quatsch] für etwas unglücklich.
Ich hab leider keine gute Idee, wie man das schöner machen kann.

Was ich meine:
ich habe in einer Kategorie 10 Staubsauger und 2x8er Muttern
Anzahl Gegenstände: 12
Das ist zwar richtig, aber wenn ich mir das von der anderen Seite anschaue habe ich 2 unterschiedliche Gegenstände.
Hier könnte irgeendwie eine Unterscheidung her aka 2/12 oder dergleichen.

**Edit**: sehe gerade bei Inventar ist das etwas anders gelöst, so ähnlich sollte das auch in der Kategorie-übersicht.

**Comment by jrie** [comment]
> **Edit**: sehe gerade bei Inventar ist das etwas anders gelöst, so ähnlich sollte das auch in der Kategorie-übersicht.

Yes, in "inventory" there is the count of positions as well as the total amounts. But I agree, it would make sense to display, in addition to the count of items, also the count of positions inside the the `/categories` view.
