### ISSUE TITLE
Packaging: create Dockerfile

### ISSUE THREAD

**Issue by n1trux** [jrie/sqstorage#5]
How nice would it be if you could simply `docker run` this project?

**Comment by X-Coder** [comment]
Hi, I created a docker-compose file for me based on mariadb's docker-entrypoint.sh and Dockerfile.template which use gpl v2 license in it's repo. As this is gpl v3 I don't know if you can use it for this project.

**Comment by jrie** [comment]
@X-Coder - the following link states, that GPLv2 is basically not compatible to GPLv3.
http://gplv3.fsf.org/wiki/index.php/Compatible_licenses#GPLv3-incompatible_licenses

From my understanding this means, that bringing the file into the project the license for this file has to be supplied together with it to. Bringing to attention that there is another license for this code parts.

**Comment by Darksider3** [comment]
I'd ask there just for permission to use it, i believe when you're kindly asking they're going to tell you it's fine @X-Coder :)

**Comment by n1trux** [comment]
> Hi, I created a docker-compose file for me based on mariadb's docker-entrypoint.sh and Dockerfile.template which use gpl v2 license in it's repo. As this is gpl v3 I don't know if you can use it for this project.

You can just use the php container for this project and have a separate MariaDB container, which wouldn't violate the GPL.

Also there's a clause in GPLv2 which means the authors can issue a statement saying "GPLv2 **or later**" but apparently they didn't. I suggest we raise that as an Issue over there.

**Comment by X-Coder** [comment]
I just created a new PR. I removed mariadb's docker-entrypoint.sh, but it will get downloaded when the container is build.

I created 3 separate containers. I preferred alpine linux, so I created new Dockerfiles for the three containers.

How to use:
Install docker + docker-compose. Run "docker-compose up -d" from within the docker subfolder.
This will create all 3 containers: mariadb + nginx + php. After this you can connect on localhost:8080.
If port 8080 is already used b ysome other process, you can change it in docker-compose.yml.
