### ISSUE TITLE
Iphones werden nach jedem Klick zurück zur login seite geleitet

### ISSUE THREAD

**Issue by rincewind0803** [jrie/sqstorage#59]
Hallo

Ich brauche mal einen Schubs in die richtig Richtung....
Wir benutzen das Programm seit ca. 6 Monaten erfolgreich für unser Tiefkühlhaus und suchen seit dem viel weniger Zeug in der Kälte ;-)
Dafür erstmal ein großes DANKESCHÖN!
Zwei der Benutzer haben allerdings ein Problem, nach erfolgreichem Login fürht jede weitere Aktion wieder zurück zum Login Screen.
 Alle anderen (Androids / Win Desktops) haben das Problem nicht.
 Nachdem dieser Fehler hier bei sonst niemandem aufzutreten scheint, vermute ich die Ursache bei meiner installation.
 Das läüft auf einem Debian stretch mit Apache / Mysql mit php 7.4 
  
Kennt sich jemand mit den Besonderheiten der Apple Geräte aus und kann mir einen Tipp geben wo der Fehler zu suche wäre?

**Comment by jrie** [comment]
Hallo!

Spontan fallen mir drei  Optionen ein die man relativ schnell testen kann. Bitte nach jedem Schritt nochmals probieren die Anwendung auf den besagten Geräten zu nutzen.

1) Deaktivieren der "PrettyURLs" in `support/dba.php` -> `$usePrettyURLs = false;`
Die Änderung erfolgt sofort und benötigt keinen Neustart. Nach Änderung der Einstellung `index.php` aufrufen.

2) Temporäres umbenennen der ".htaccess" zu einem anderen Namen. Diese befindet sich im Hauptverzeichniss der Installation. Der Schritt verhindert, das Apache die angefragten URLs intern umwandelt.

Wenn dies keine Abhilfe schafft, bitte testweise das Benutzersystem deaktivieren:

3) Deaktivierung der Benutzerauthentifizierung. In `support/dba.php` -> `$useRegistration = false;` setzen.
Nach Änderung der Einstellung `index.php` aufrufen.

**Comment by rincewind0803** [comment]
Vielen Dank für die schnelle Antwort !

Leider hat keiner der Tipps finktioniert, PrettyUrls waren aus, habe ich mal testweise eingeschaltet, gleiches Phänomen.
Wenn ich die .htaccess weg nehme, ist für alle die Navigation kaputt... index statt index.php.
Benutzerauthentifizierung abschalten kann ich erst am Wochenende testen....

**Comment by rincewind0803** [comment]
So, weitere Tests sind erfolgt....
Entfernen der .htaccess hat dazu geführt das auf dem iphone (und das ist neu) zwar das Eintragen von Dingen möglich ist, jedoch nicht das Löschen. an der Stelle wo bei Android/PC die Abfrage (Wirklich löschen) kommt werden die Iphones zurück zum Login geschickt.

**Comment by jrie** [comment]
Hallo, ich habe leider kein iPhone zur Hand und habe nicht die Möglichkeit dies zu testen.
Tritt der Fehler auch bei deaktivierter Benutzerschnittstelle auf?

**Comment by jrie** [comment]
Could not reproduce, closing for now.
