### ISSUE TITLE
Maximize thumbnails

### ISSUE THREAD

**Issue by Steev1** [jrie/sqstorage#93]
Hi, as you know and also thanks to you I am a user of your sqStorage. I have already written many suggestions for improvement in the ngb forum, now I also have one here for the Github. That with the small thumbnails is good, but it would be nice if you could enlarge this thumbnail, so that I then see the whole desktop image. I attach a screenshot and have painted a maximize button in the top right corner of the image. Something like that I mean.
![thumb-bigsize-button](https://user-images.githubusercontent.com/106469544/186917670-8e6314e6-0e65-48d5-bac5-8f7d55161620.jpg)

**Comment by jrie** [comment]
A "lightbox"-gallery has been added, which allows to display the bigger version of an image. Also the gallery allows to switch through all pictures added to an item:
Closing in reason of commit 8db22f69523ad5e67edaa7d45b2441f9266bb015 .
