### ISSUE TITLE
Probleme mit PHP8.1.10 

### ISSUE THREAD

**Issue by Launhardt** [jrie/sqstorage#99]
Tritt vor allem auf wenn eine Kategorie keinen Inhalt mehr hat.

Warning: Undefined array key "items" in \xxx\htdocs\sqstorage\inventory.php on line 502
Fatal error: Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in \xxx\xxx\sqstorage\inventory.php:502 Stack trace: #0 {main} thrown in \xxx\htdocs\sqstorage\inventory.php on line 502

**Comment by jrie** [comment]
Fixed in commit 34f8dea . Thanks for the report! :+1:
